name: camera_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  camera: ^0.11.2
  path_provider: ^2.1.3
  path: ^1.9.0
  gallery_saver: ^2.3.2
  provider: ^6.1.2

  # UI helpers
  flutter_spinkit: ^5.2.0
  google_fonts: ^4.0.4
